# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
    - knitr
    - rmarkdown
    - testthat
    - covr
    - devtools
    - usethis
    - stats
    - MASS
bioc_r_packages:
    - BiocStyle
after_success:
    - Rscript -e 'covr::codecov()'
os:
    - linux
r:
    - bioc-devel
notifications:
  email:
    on_success: change
    on_failure: change
